Develop
viktoria-anatsko/Automation-testing-project-testmonitor.com pull request #11
Opened 2023-09-20 17:21 UTC by viktoria-anatsko

Added part of the project.

2023-10-02 06:49 UTC, wildpioneer requested changes

2023-10-02 06:49 UTC, wildpioneer commented on pom.xml
> +            <version>7.7.1</version>
Вынести в property

2023-10-02 06:49 UTC, wildpioneer commented on src/test/java/tests/ui/UploadTest.java
> +            fileUploadElement.sendKeys(pathToFile.substring(1, pathToFile.length()));
У меня это не работает. Я уже 3 раза показывал как должно быть

2023-10-02 06:49 UTC, wildpioneer commented on src/test/java/tests/ui/TooltipTest.java
> +                ("//div[2]/div/div[contains(text(), 'Chrome')]")).isDisplayed());
??? Такой страшный селектор в тесте - исправить

2023-10-02 06:49 UTC, wildpioneer commented on src/test/java/tests/api/NegativeGetProjectTest.java
> +        given()
Почему не используются Adaptep для вызовов?

2023-10-02 06:49 UTC, wildpioneer commented on src/test/java/tests/ui/BoundaryValueTest.java
> +        List<String> namesOfTeamsList = new ArrayList<>();
Необходимо вынести создание тестовых данных в отдельный хелпер например, или вообще в класс

2023-10-02 06:49 UTC, wildpioneer commented on src/test/java/tests/ui/BoundaryValueTest.java
> +        int lengthOfTeamName2 = teamName2.length();
Обоснованно ли здесь использование однорозаовой переменной? Почему сразу не использовать teamName2.length()?

2023-10-02 06:49 UTC, wildpioneer commented on src/test/java/tests/ui/UploadTest.java
> +        WebElement fileUploadElement = waitService.waitForExists(By.xpath("//input[@type='file']"));
Использование локаторов в самом тесте - не допустимо

2023-10-03 17:32 UTC, viktoria-anatsko commented
Правки внесены.

2023-10-04 09:07 UTC, wildpioneer commented
Проверено

2023-10-04 09:08 UTC, merged